//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fingerprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class absen
    {
        public string pegawai_id { get; set; }
        public System.DateTime absen_tanggal { get; set; }
        public string absen_hari { get; set; }
        public string absen_izin { get; set; }
        public Nullable<System.TimeSpan> absen_telat { get; set; }
        public Nullable<System.TimeSpan> absen_masuk { get; set; }
        public Nullable<System.TimeSpan> absen_pulang { get; set; }
        public Nullable<System.TimeSpan> absen_istirahat { get; set; }
        public Nullable<System.TimeSpan> absen_kembali { get; set; }
        public Nullable<System.TimeSpan> absen_lembur { get; set; }
        public Nullable<System.TimeSpan> absen_lembur_pulang { get; set; }
        public bool upload { get; set; }
    
        public virtual pegawai pegawai { get; set; }
    }
}
