
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fingerprint
{

using System;
    using System.Collections.Generic;
    
public partial class aturan
{

    public int aturan_hari { get; set; }

    public bool aturan_kegiatan { get; set; }

    public System.TimeSpan aturan_jam_masuk { get; set; }

    public System.TimeSpan aturan_jam_pulang { get; set; }

    public System.TimeSpan aturan_jam_masuk_khusus { get; set; }

    public System.TimeSpan aturan_jam_pulang_khusus { get; set; }

}

}
