//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fingerprint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fingerprintEntities : DbContext
    {
        public fingerprintEntities()
            : base("name=fingerprintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<absen> absens { get; set; }
        public virtual DbSet<aturan> aturans { get; set; }
        public virtual DbSet<hari_khusus> hari_khusus { get; set; }
        public virtual DbSet<izin> izins { get; set; }
        public virtual DbSet<libur> liburs { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<mesin> mesins { get; set; }
        public virtual DbSet<pegawai> pegawais { get; set; }
        public virtual DbSet<upload_download> upload_download { get; set; }
    }
}
