//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fingerprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class izin
    {
        public string pegawai_id { get; set; }
        public System.DateTime izin_tanggal { get; set; }
        public string izin_jenis { get; set; }
        public string izin_keterangan { get; set; }
    
        public virtual pegawai pegawai { get; set; }
    }
}
