
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fingerprint
{

using System;
    using System.Collections.Generic;
    
public partial class libur
{

    public System.DateTime libur_tanggal { get; set; }

    public string libur_keterangan { get; set; }

}

}
