
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fingerprint
{

using System;
    using System.Collections.Generic;
    
public partial class log
{

    public int log_id { get; set; }

    public string pegawai_id { get; set; }

    public System.DateTime log_tanggal { get; set; }

    public System.TimeSpan log_jam { get; set; }

    public string log_kode { get; set; }

    public string log_keterangan { get; set; }

    public string log_status { get; set; }



    public virtual pegawai pegawai { get; set; }

}

}
