//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fingerprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesin
    {
        public int mesin_id { get; set; }
        public string mesin_nama { get; set; }
        public string mesin_ip { get; set; }
        public string mesin_key { get; set; }
        public string mesin_sn { get; set; }
    }
}
