//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fingerprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload_download
    {
        public int upload_download_id { get; set; }
        public System.DateTime upload_download_tanggal { get; set; }
        public string upload_download_jenis { get; set; }
        public string upload_download_keterangan { get; set; }
    }
}
